/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manuel_medina;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Barra_Herramientas = new javax.swing.JToolBar();
        Linea = new javax.swing.JButton();
        Rectangulo = new javax.swing.JButton();
        Elipse = new javax.swing.JButton();
        Panel_Inferior = new javax.swing.JPanel();
        ColoryRelleno = new javax.swing.JPanel();
        Relleno_panel = new javax.swing.JPanel();
        Relleno_check = new javax.swing.JCheckBox();
        Colores = new javax.swing.JPanel();
        Colores1 = new javax.swing.JPanel();
        Negro = new javax.swing.JButton();
        Rojo = new javax.swing.JButton();
        Azul = new javax.swing.JButton();
        Colores2 = new javax.swing.JPanel();
        Blanco = new javax.swing.JButton();
        Amarillo = new javax.swing.JButton();
        Verde = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Lienzo = new javax.swing.JPanel();
        BarraMenu = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        Barra_Herramientas.setRollover(true);

        Linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/linea.png"))); // NOI18N
        Linea.setFocusable(false);
        Linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Linea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Barra_Herramientas.add(Linea);

        Rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rectangulo.png"))); // NOI18N
        Rectangulo.setFocusable(false);
        Rectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Rectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Barra_Herramientas.add(Rectangulo);

        Elipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/elipse.png"))); // NOI18N
        Elipse.setFocusable(false);
        Elipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Elipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Barra_Herramientas.add(Elipse);

        getContentPane().add(Barra_Herramientas, java.awt.BorderLayout.PAGE_START);

        Panel_Inferior.setLayout(new java.awt.BorderLayout());

        ColoryRelleno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ColoryRelleno.setLayout(new java.awt.BorderLayout());

        Relleno_panel.setLayout(new java.awt.BorderLayout());

        Relleno_check.setText("Relleno");
        Relleno_panel.add(Relleno_check, java.awt.BorderLayout.CENTER);

        ColoryRelleno.add(Relleno_panel, java.awt.BorderLayout.EAST);

        Colores.setLayout(new java.awt.BorderLayout());

        Negro.setBackground(new java.awt.Color(0, 0, 0));
        Negro.setMaximumSize(new java.awt.Dimension(20, 20));
        Negro.setMinimumSize(new java.awt.Dimension(20, 20));
        Negro.setPreferredSize(new java.awt.Dimension(20, 20));
        Colores1.add(Negro);

        Rojo.setBackground(new java.awt.Color(255, 0, 0));
        Rojo.setForeground(new java.awt.Color(255, 0, 0));
        Rojo.setFocusable(false);
        Rojo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Rojo.setMaximumSize(new java.awt.Dimension(20, 20));
        Rojo.setMinimumSize(new java.awt.Dimension(20, 20));
        Rojo.setPreferredSize(new java.awt.Dimension(20, 20));
        Rojo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RojoActionPerformed(evt);
            }
        });
        Colores1.add(Rojo);

        Azul.setBackground(java.awt.Color.blue);
        Azul.setForeground(java.awt.Color.blue);
        Azul.setFocusable(false);
        Azul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Azul.setMaximumSize(new java.awt.Dimension(20, 20));
        Azul.setMinimumSize(new java.awt.Dimension(20, 20));
        Azul.setPreferredSize(new java.awt.Dimension(20, 20));
        Azul.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Colores1.add(Azul);

        Colores.add(Colores1, java.awt.BorderLayout.NORTH);

        Blanco.setMaximumSize(new java.awt.Dimension(20, 20));
        Blanco.setMinimumSize(new java.awt.Dimension(20, 20));
        Blanco.setPreferredSize(new java.awt.Dimension(20, 20));
        Blanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlancoActionPerformed(evt);
            }
        });
        Colores2.add(Blanco);

        Amarillo.setBackground(java.awt.Color.yellow);
        Amarillo.setFocusable(false);
        Amarillo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Amarillo.setMaximumSize(new java.awt.Dimension(20, 20));
        Amarillo.setMinimumSize(new java.awt.Dimension(20, 20));
        Amarillo.setPreferredSize(new java.awt.Dimension(20, 20));
        Amarillo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Amarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmarilloActionPerformed(evt);
            }
        });
        Colores2.add(Amarillo);

        Verde.setBackground(java.awt.Color.green);
        Verde.setFocusable(false);
        Verde.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Verde.setMaximumSize(new java.awt.Dimension(20, 20));
        Verde.setMinimumSize(new java.awt.Dimension(20, 20));
        Verde.setPreferredSize(new java.awt.Dimension(20, 20));
        Verde.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerdeActionPerformed(evt);
            }
        });
        Colores2.add(Verde);

        Colores.add(Colores2, java.awt.BorderLayout.SOUTH);

        ColoryRelleno.add(Colores, java.awt.BorderLayout.WEST);

        Panel_Inferior.add(ColoryRelleno, java.awt.BorderLayout.PAGE_START);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Barra de estado");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Panel_Inferior.add(jLabel1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(Panel_Inferior, java.awt.BorderLayout.PAGE_END);

        Lienzo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout LienzoLayout = new javax.swing.GroupLayout(Lienzo);
        Lienzo.setLayout(LienzoLayout);
        LienzoLayout.setHorizontalGroup(
            LienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );
        LienzoLayout.setVerticalGroup(
            LienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );

        getContentPane().add(Lienzo, java.awt.BorderLayout.CENTER);

        Archivo.setText("File");

        jMenuItem1.setText("jMenuItem1");
        Archivo.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        Archivo.add(jMenuItem2);

        BarraMenu.add(Archivo);

        jMenu2.setText("Edit");

        jMenuItem3.setText("jMenuItem3");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        jMenu2.add(jMenuItem4);

        BarraMenu.add(jMenu2);

        setJMenuBar(BarraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BlancoActionPerformed

    private void AmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmarilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmarilloActionPerformed

    private void VerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerdeActionPerformed

    private void RojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RojoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RojoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Amarillo;
    private javax.swing.JMenu Archivo;
    private javax.swing.JButton Azul;
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JToolBar Barra_Herramientas;
    private javax.swing.JButton Blanco;
    private javax.swing.JPanel Colores;
    private javax.swing.JPanel Colores1;
    private javax.swing.JPanel Colores2;
    private javax.swing.JPanel ColoryRelleno;
    private javax.swing.JButton Elipse;
    private javax.swing.JPanel Lienzo;
    private javax.swing.JButton Linea;
    private javax.swing.JButton Negro;
    private javax.swing.JPanel Panel_Inferior;
    private javax.swing.JButton Rectangulo;
    private javax.swing.JCheckBox Relleno_check;
    private javax.swing.JPanel Relleno_panel;
    private javax.swing.JButton Rojo;
    private javax.swing.JButton Verde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
